// <auto-generated />
using System;
using Infrastructure.ListaCompras.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.ListaCompras.Migrations
{
    [DbContext(typeof(ListaCompras_DbContext))]
    partial class ListaCompras_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.ListaCompras.Entities.Historico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("ListaId")
                        .HasColumnType("integer");

                    b.Property<int?>("MercadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("PrecoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<string>("Registro")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ListaId");

                    b.HasIndex("MercadoId");

                    b.HasIndex("PrecoId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Historico");
                });

            modelBuilder.Entity("Domain.ListaCompras.Entities.Lista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataListaCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Lista");
                });

            modelBuilder.Entity("Domain.ListaCompras.Entities.Mercado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("HorarioFuncionamento")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Mercado");
                });

            modelBuilder.Entity("Domain.ListaCompras.Entities.Preco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Desconto")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Preco");
                });

            modelBuilder.Entity("Domain.ListaCompras.Entities.PrecoMercado", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("MercadoId")
                        .HasColumnType("integer");

                    b.Property<int>("PrecoId")
                        .HasColumnType("integer");

                    b.HasKey("ProdutoId", "MercadoId");

                    b.HasIndex("MercadoId");

                    b.HasIndex("PrecoId");

                    b.ToTable("PrecoMercado");
                });

            modelBuilder.Entity("Domain.ListaCompras.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateOnly>("Validade")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Domain.ListaCompras.Entities.ProdutoLista", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("ListaId")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("ProdutoId", "ListaId");

                    b.HasIndex("ListaId");

                    b.HasIndex("StatusId");

                    b.ToTable("ProdutoLista");
                });

            modelBuilder.Entity("Domain.ListaCompras.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Pendente"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Comprado"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Indisponível"
                        });
                });

            modelBuilder.Entity("Domain.ListaCompras.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Domain.ListaCompras.Entities.UsuarioLista", b =>
                {
                    b.Property<int>("ListaId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("ListaId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioLista");
                });

            modelBuilder.Entity("Domain.ListaCompras.Entities.Historico", b =>
                {
                    b.HasOne("Domain.ListaCompras.Entities.Lista", "Lista")
                        .WithMany()
                        .HasForeignKey("ListaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.ListaCompras.Entities.Mercado", "Mercado")
                        .WithMany("Historicos")
                        .HasForeignKey("MercadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.ListaCompras.Entities.Preco", "Preco")
                        .WithMany("Historicos")
                        .HasForeignKey("PrecoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.ListaCompras.Entities.Produto", "Produto")
                        .WithMany("Historicos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.ListaCompras.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.ListaCompras.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lista");

                    b.Navigation("Mercado");

                    b.Navigation("Preco");

                    b.Navigation("Produto");

                    b.Navigation("Status");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.ListaCompras.Entities.PrecoMercado", b =>
                {
                    b.HasOne("Domain.ListaCompras.Entities.Mercado", "Mercado")
                        .WithMany("PrecoMercados")
                        .HasForeignKey("MercadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.ListaCompras.Entities.Preco", "Preco")
                        .WithMany("PrecoMercados")
                        .HasForeignKey("PrecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.ListaCompras.Entities.Produto", "Produto")
                        .WithMany("PrecoMercados")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mercado");

                    b.Navigation("Preco");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Domain.ListaCompras.Entities.ProdutoLista", b =>
                {
                    b.HasOne("Domain.ListaCompras.Entities.Lista", "Lista")
                        .WithMany("ProdutoListas")
                        .HasForeignKey("ListaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.ListaCompras.Entities.Produto", "Produto")
                        .WithMany("ProdutoListas")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.ListaCompras.Entities.Status", "Status")
                        .WithMany("ProdutoListas")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lista");

                    b.Navigation("Produto");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Domain.ListaCompras.Entities.UsuarioLista", b =>
                {
                    b.HasOne("Domain.ListaCompras.Entities.Lista", "Lista")
                        .WithMany("UsuarioListas")
                        .HasForeignKey("ListaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.ListaCompras.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioListas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lista");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.ListaCompras.Entities.Lista", b =>
                {
                    b.Navigation("ProdutoListas");

                    b.Navigation("UsuarioListas");
                });

            modelBuilder.Entity("Domain.ListaCompras.Entities.Mercado", b =>
                {
                    b.Navigation("Historicos");

                    b.Navigation("PrecoMercados");
                });

            modelBuilder.Entity("Domain.ListaCompras.Entities.Preco", b =>
                {
                    b.Navigation("Historicos");

                    b.Navigation("PrecoMercados");
                });

            modelBuilder.Entity("Domain.ListaCompras.Entities.Produto", b =>
                {
                    b.Navigation("Historicos");

                    b.Navigation("PrecoMercados");

                    b.Navigation("ProdutoListas");
                });

            modelBuilder.Entity("Domain.ListaCompras.Entities.Status", b =>
                {
                    b.Navigation("ProdutoListas");
                });

            modelBuilder.Entity("Domain.ListaCompras.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioListas");
                });
#pragma warning restore 612, 618
        }
    }
}
